steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/FastApi-Google-Cloud-Run', '.' ]
  id: 'build-image-service'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/fastapi-google-cloud-run' ]
  id: 'push-image-to-container-registry'
  waitFor: ['build-image-service']  
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'microservice'
  - '--image'
  - 'gcr.io/$PROJECT_ID/fastapi-google-cloud-run'
  - '--region'
  - 'us-east4'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  waitFor: ['push-image-to-container-registry']
  id: 'deploy-to-cloud-run'
  
